### GET request to Booking Servlet - getAllBookings
GET http://localhost:8080/hw4/booking

### GET request to Booking Servlet - getByUserame
GET http://localhost:8080/hw4/booking?action=resource&value=3

### GET request to Booking Servlet - getByUserame
GET http://localhost:8080/hw4/booking?action=date&value=2024-06-21T12:00:00

### GET request to Booking Servlet - getByUserame
GET http://localhost:8080/hw4/booking?action=user&value=mikki

### Post request to Booking Servlet - createUser
POST http://localhost:8080/hw4/booking
Content-Type: application/json

{
  "resourceId": 3,
  "resourceType": "H",
  "startDateTimeString": "2024-07-21T19:00:00",
  "endDateTimeString": "2024-07-21T21:00:00"
}

### Delete request to Booking Servlet - authorize
DELETE http://localhost:8080/hw4/booking/3
